#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
git lfs post-commit "$@"

CURRENT_BRANCH=$(git branch --show-current)
# Если релизная ветка (имеет имя вида ERP_2.4.13.209), тогда выполняем скрипт проверки регл. форм
if [[ $CURRENT_BRANCH =~ ERP_[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]]
then
	TEMP_FILE=$(mktemp)
	git diff --name-only --diff-filter=AC HEAD^ HEAD | grep --ignore-case Config/Reports/.*/ФормаОтчета.*\.xml >> $TEMP_FILE
	python "D:\Users\Common\git\devops\git\check_reg_reports.py" $PWD $TEMP_FILE
	rm --force $TEMP_FILE
fi