#!/bin/sh

export LANG=C.UTF-8

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep "Configuration.xml")
if [ -n "$CHANGED_FILES" ]
then
	python "D:\Users\Common\git\devops\git\configuration_fix.py" $PWD $CHANGED_FILES
fi
